Passing default value for videoindexer_api_key
Azure/ai-hub pull request #163
Opened 2024-05-03 18:18 UTC by uday31in

**Proposed changes**:
- ...

2024-05-03 21:58 UTC, uday31in commented
<img width="776" alt="Screenshot 2024-05-03 at 22 58 01" src="https://github.com/Azure/ai-hub/assets/14359777/d4d7aae4-a22a-4a54-b16a-2c1d5818f138">

@marvinbuss  - to add access policies

2024-05-04 13:29 UTC, uday31in commented
<img width="735" alt="image" src="https://github.com/Azure/ai-hub/assets/14359777/15cc79b8-dcf4-43e0-bbf8-38405d0e25fd">

2024-05-04 19:07 UTC, marvinbuss requested changes
Please review comments.

2024-05-04 19:07 UTC, marvinbuss commented on infrastructure/terraform/modules/logicapp/logicapp_apiconnections.tf
> +}
I have done the same using azapi. If you don't mind let's use azapi as ARM templates usually create some challenges from a plan perspective.

2024-05-04 19:07 UTC, marvinbuss commented on infrastructure/terraform/modules/storageaccount/output.tf
> +}
I worked on a solution to generate SAS using HTTP. Also, this does not use account level SAS keys. I consider this more secure. What are your thoughts? Let's sync on that.

2024-05-05 11:46 UTC, uday31in commented
Please merge your changes and close this PR

2024-05-05 15:41 UTC, marvinbuss commented on infrastructure/terraform/modules/logicapp/logicapp_apiconnections.tf
> +}
This PR now includes the `azapi` resource: https://github.com/Azure/ai-hub/pull/166

2024-05-05 15:41 UTC, marvinbuss commented
> Please merge your changes and close this PR

Will close this once we merged the other PR.

2024-05-05 19:18 UTC, marvinbuss commented
Superseded by https://github.com/Azure/ai-hub/pull/166

2024-05-05 19:18 UTC, closed without merging